services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    restart: on-failure
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    restart: on-failure
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443 # Host can access site through port 443 into containters 443
    restart: on-failure
    volumes:
      - wp-data:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  db-data:
    name: "db-data"
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/database"
  wp-data:
    name: "wp-data"
    driver_opts:
      type: none
      o: bind
      device: "/home/${USER}/data/wordpress"

networks:
  inception:
    name: inception
    driver: bridge
