version: '3'

services:
  nginx:
    build: ./requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception

networks:
  name: inception
  driver: bridge
